name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run prettier
      - run: docker run -d -v $(pwd)/test/volumes/sftp/etc/ssh/sshd_config:/etc/ssh/sshd_config:rw -v $(pwd)/test/volumes/sftp/home/fred/files:/home/fred/files:rw -p 10022:22 atmoz/sftp:alpine fred:password:1001
      - run: sleep 5
      - run: npm test

  code-climate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run prettier
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: docker run -d -v $(pwd)/test/volumes/sftp/etc/ssh/sshd_config:/etc/ssh/sshd_config:rw -v $(pwd)/test/volumes/sftp/home/fred/files:/home/fred/files:rw -p 10022:22 atmoz/sftp:alpine fred:password:1001
      - run: sleep 5
      - run: npm run coverage
      - run: ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
      - run: ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
