name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sftp:
        image: atmoz/sftp:alpine
        ports:
          - 10022:22
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run prettier
