name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run prettier
      - run: docker run -d -v $(pwd)/test/volumes/sftp/etc/ssh/sshd_config:/etc/ssh/sshd_config:rw -v $(pwd)/test/volumes/sftp/home/fred/files:/home/fred/files:rw -p 10022:22 atmoz/sftp:alpine fred:password:1001
      - run: npm test
